import os
import openai
import gradio as gr


openai.api_key = os.getenv("OPENAI_SECRET_KEY")
openai.organization = os.getenv("OPENAI_ORGANIZATION_ID")


def create_file():
    file = openai.File.create(
        file=open("promptsforgpt_prepared.jsonl", "rb"), # generated by generatepromptsdataset.py
        purpose='fine-tune'
    )


def create_finetuned_model(): # read more in https://beta.openai.com/docs/guides/fine-tuning
    finetuned = openai.FineTune.create(
        model="curie", 
        training_file="file-VPmwE5j3yEj271qLr79uUOrZ", #FIXME Put in ID generated from create_file
        n_epochs=1
    )


def get_response(Product, Discount, Features):
    prompt = "Make a description about a " + Product + "with the features " + Features + "going for a price discount of " + Discount
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt=prompt,
        max_tokens = 150,
        temperature=0
    )

    clean = response.get('choices')

    return clean[0]['text']

demo = gr.Interface(
    fn=get_response, 
    inputs=["text", "text", "text"],
    outputs="text")

if __name__ == "__main__":
    demo.launch(share=True)
